[project]
name = "aiothreading"
dynamic = ["version"]
description = "AsyncIO version of the standard threading module"
readme = "README.md"
authors = [
    { name = "Vizonex", email="VizonexBusiness@gmail.com" },
    { name = "x42005e1f" }
]
requires-python = ">=3.10"
dependencies = [
    "aiologic>=0.15.0",
    "taskgroup>=0.2.2; python_version<'3.11'",
]
keywords=["aiothreading", "threading", "asyncio"]

classifiers=[
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

]

[tool.setuptools.dynamic]
version = {attr = "aiothreading.__version__"}

[build-system]
requires = ["setuptools"]

[project.urls]
    homepage = "https://github.com/Vizonex/aiothreading"
    repository = "https://github.com/Vizonex/aiothreading.git"

[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py310"
fix = true

[tool.ruff.lint]
select = [
    "E",
    "W",
    "I",
    "F",
    "UP"
]

