# NOTE: Our Deprecated param wrapper around threadpool ruins 
# Type-Checkers from seeing what arguments are being used 
# with `ThreadPool.__init__`, (Mainly Found on the VSCode pyright extension), this was my solution - Vizonex

import asyncio
from .core import Thread as Thread
from .scheduler import Scheduler as Scheduler
from .types import LoopInitializer as LoopInitializer, ProxyException as ProxyException, R as R, T as T
from .utils import deprecated_param as deprecated_param
from _typeshed import Incomplete
from aiologic import SimpleQueue
from concurrent.futures import Future
from types import TracebackType
from typing import Any, AsyncIterable, AsyncIterator, Awaitable, Callable, Coroutine, Generator, Sequence

MAX_TASKS_PER_CHILD: int
CHILD_CONCURRENCY: int

class ThreadPoolWorker(Thread[None]):
    def __init__(self, tx: SimpleQueue[tuple[Callable[..., Coroutine[Any, Any, Any]], Sequence[Any], dict[str, Any], Future[Any]] | None], ttl: int = ..., concurrency: int = ..., *, exception_handler: Callable[[BaseException], None] | None = None, **kwargs: Any) -> None: ...
    async def run(self) -> None: ...
    def key(self) -> int: ...
    @property
    def pending(self) -> int: ...

class ThreadPoolResult(Awaitable[Sequence[T]], AsyncIterable[T]):
    futures: Incomplete
    def __init__(self, futures: Sequence[asyncio.Future[T]]) -> None: ...
    def __await__(self) -> Generator[Any, Any, Sequence[T]]: ...
    async def results(self) -> Sequence[T]: ...
    async def __aiter__(self) -> AsyncIterator[T]: ...
    async def results_generator(self) -> AsyncIterator[T]: ...

class ThreadPool:
    def __init__(self, threads: int | None = None, initializer: Callable[..., Any] | None = None, initargs: Sequence[Any] = (), maxtasksperchild: int = ..., childconcurrency: int = ..., queuecount: int | None = None, scheduler: Scheduler | None = None, loop_initializer: LoopInitializer | None = None, exception_handler: Callable[[BaseException], None] | None = None) -> None: ...
    async def __aenter__(self) -> ThreadPool: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def submit(self, func: Callable[..., Coroutine[Any, Any, R]], /, *args: Any, **kwargs: Any) -> asyncio.Future[R]: ...
    async def apply(self, func: Callable[..., Coroutine[Any, Any, R]], args: Sequence[Any] | None = None, kwds: dict[str, Any] | None = None) -> R: ...
    def map(self, func: Callable[[T], Coroutine[Any, Any, R]], iterable: Sequence[T]) -> ThreadPoolResult[R]: ...
    def starmap(self, func: Callable[..., Coroutine[Any, Any, R]], iterable: Sequence[Sequence[T]]) -> ThreadPoolResult[R]: ...
    def close(self) -> None: ...
    def terminate(self) -> None: ...
    async def join(self) -> None: ...
